//
// Created by Niloy Farhan on 13/1/24.
//

#ifndef STREAM_INSERTION_AND_EXTRACTION_OPERATOR_MYSTRING_H
#define STREAM_INSERTION_AND_EXTRACTION_OPERATOR_MYSTRING_H


class Mystring {

};


#endif //STREAM_INSERTION_AND_EXTRACTION_OPERATOR_MYSTRING_H
