//
// Created by Niloy Farhan on 15/1/24.
//

#ifndef REDEFINING_BASE_CLASS_METHOD_SAVINGS_ACCOUNT_H
#define REDEFINING_BASE_CLASS_METHOD_SAVINGS_ACCOUNT_H


class Savings_Account {

};


#endif //REDEFINING_BASE_CLASS_METHOD_SAVINGS_ACCOUNT_H
